### ISSUE TITLE
[FR] Config file Jinja2 support

### ISSUE THREAD

**Issue by JohnPreston** [JohnPreston/kafka-overwatch#3]
The input config file could use the Jinja2 template engine to interpolate values.

For example

```yaml
clusters:
  nasa:
    cluster_config:
      kafka:
        bootstrap.servers: {{ env_var('NASA_BOOTSTRAP_URL') }}
        security.protocol: sasl_ssl
        sasl.mechanisms: OAUTHBEARER
        sasl.oauthbearer.method: oidc
        sasl.oauthbearer.token.endpoint.url: https://auth.gcn.nasa.gov/oauth2/token
        sasl.oauthbearer.scope: gcn.nasa.gov/kafka-public-consumer
        client.id: kafka-overwatch-dev
    reporting_config:
      local: ./nasa_generated_reports
      evaluation_period_in_seconds: 300
```
