### ISSUE TITLE
[FR] Support clusters discovery with SaaS providers

### ISSUE THREAD

**Issue by JohnPreston** [JohnPreston/kafka-overwatch#6]
As a Kafka SaaS customer, I might have the ability to do clusters discovery within my account.
From there, I'd like to dynamically import clusters to monitor. Where possible, if enabled, kafka-overwatch can automatically create a new Kafka principal, set access requirements for it on the resources (read-only).

for example

```yaml

providers:
  confluent_cloud: {}
  aiven: {}
  conduktor_gateway: {}
```

Conduktor Gateway, although not a SaaS, when used with multi-clusters, is a multi-tenancy provider of its own.
